version: '3'

services:
    database:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: planisto
            POSTGRES_PASSWORD: very_secret
            POSTGRES_DB: planisto
        volumes:
            - DATA:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    DATA: